apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/graphql/

images:
  - name: Tmaster
    newName: "docker.pkg.github.com/j75689/tmaster/tmaster"
    newTag: "latest"
