apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: Tmaster-initializer
    app.kubernetes.io/name: Tmaster-initializer
    app: Tmaster-initializer
  name: Tmaster-initializer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: Tmaster-initializer
      app.kubernetes.io/instance: Tmaster-initializer
      app.kubernetes.io/name: Tmaster-initializer
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: Tmaster-initializer
        app.kubernetes.io/instance: Tmaster-initializer
        app.kubernetes.io/name: Tmaster-initializer
        auth-filter-injection: enabled
        accesslog-filter-injection: enabled
    spec:
      containers:
        - image: Tmaster
          imagePullPolicy: Always
          name: Tmaster-initializer
          args:
            - "initializer"
            - "--config"
            - "config/initializer.conf.yaml"
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          resources: {}
          securityContext:
            capabilities: {}
          volumeMounts:
            - mountPath: /Tmaster/config
              name: config
            - mountPath: /Tmaster/pubsub_credentials.json
              name: pubsub-credentials
              subPath: pubsub_credentials.json
      initContainers:
        - image: Tmaster
          imagePullPolicy: Always
          name: Tmaster-migration
          args:
            - "migrate"
            - "--config"
            - "config/initializer.conf.yaml"
          volumeMounts:
            - mountPath: /Tmaster/config
              name: config
        - image: Tmaster
          imagePullPolicy: Always
          name: Tmaster-initmq
          args:
            - "initmq"
            - "initializer"
            - "--config"
            - "config/initializer.conf.yaml"
          volumeMounts:
            - mountPath: /Tmaster/config
              name: config
            - mountPath: /Tmaster/pubsub_credentials.json
              name: pubsub-credentials
              subPath: pubsub_credentials.json
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      imagePullSecrets:
        - name: github
      terminationGracePeriodSeconds: 30
      volumes:
        - name: config
          secret:
            defaultMode: 420
            secretName: Tmaster-initializer-config
        - name: pubsub-credentials
          secret:
            defaultMode: 420
            secretName: Tmaster-pubsub-credentials
