apiVersion: v1
kind: Service
metadata:
  name: Tmaster-graphql
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/instance: Tmaster-graphql
    app.kubernetes.io/name: Tmaster-graphql

