name: Checker

on:
  push:
    branches:
      - main
      
  pull_request:
    branches:
      - main

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  test:
    strategy:
      matrix:
        go-version: [1.16.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
        
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Wire
      run: |
        go mod tidy
        go get github.com/google/wire/cmd/wire
        wire ./service/...

    - name: Test
      run: go test ./...

    - name: Run Gosec Security Scanner
      uses: securego/gosec@master
      with:
        args: -quiet -confidence high -severity high ./...
